import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FormAdminLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FormAdminLaporan
     */
    
    DefaultTableModel tableModel;

    
    public FormAdminLaporan() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        tampilkanDataPemesanan();
    }
    
    private void tampilkanDataPemesanan() {
        try {
            Connection conn = Koneksi.getConnection();
String query = "SELECT p.id_pemesanan, u.nama, p.tanggalpemesanan, p.status " +
               "FROM pemesanan p " +
               "JOIN users u ON p.id_user = u.id_user";


            java.sql.PreparedStatement stmt = conn.prepareStatement(query);
            java.sql.ResultSet rs = stmt.executeQuery();

            String[] kolom = {"ID", "Nama", "Tanggal", "Status", "Opsi"};
            tableModel = new DefaultTableModel(kolom, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 4;
                }
            };

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_pemesanan"),
                    rs.getString("nama"),
                    rs.getDate("tanggalpemesanan"),
                    rs.getString("status"),
                    "" 
                };
                tableModel.addRow(row);
            }

            tableLaporanFormAdminLaporan.setModel(tableModel);
            TableColumnModel columnModel = tableLaporanFormAdminLaporan.getColumnModel();
            columnModel.getColumn(0).setMinWidth(0);
            columnModel.getColumn(0).setMaxWidth(0);
            columnModel.getColumn(0).setWidth(0);
            
            columnModel.getColumn(1).setPreferredWidth(70); // Nama
            columnModel.getColumn(2).setPreferredWidth(100); // Tanggal
            columnModel.getColumn(3).setPreferredWidth(100); // Status
            columnModel.getColumn(4).setPreferredWidth(150); // Opsi

            tableLaporanFormAdminLaporan.setRowHeight(30);
            
            tableLaporanFormAdminLaporan.getColumn("Opsi").setCellRenderer(new TombolRenderer());
            tableLaporanFormAdminLaporan.getColumn("Opsi").setCellEditor(new TombolEditor(new javax.swing.JCheckBox(), tableLaporanFormAdminLaporan));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data pemesanan.");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfilFormAdminLaporan = new javax.swing.JButton();
        btnBerandaFormAdminLaporan = new javax.swing.JButton();
        btnKelolaDataFormAdminLaporan = new javax.swing.JButton();
        btnKelolaDestinasiFormAdminLaporan = new javax.swing.JButton();
        btnLaporanFormAdminLaporan = new javax.swing.JButton();
        btnKeluarFormAdminLaporan = new javax.swing.JButton();
        scrollPaneTableLaporanFormAdminLaporan = new javax.swing.JScrollPane();
        tableLaporanFormAdminLaporan = new javax.swing.JTable();
        bgFormAdminLaporan = new javax.swing.JLabel();

        setTitle("Tripnesia - Dashboard Admin - Laporan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfilFormAdminLaporan.setForeground(java.awt.Color.white);
        btnProfilFormAdminLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profil icon.png"))); // NOI18N
        btnProfilFormAdminLaporan.setBorderPainted(false);
        btnProfilFormAdminLaporan.setContentAreaFilled(false);
        btnProfilFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfilFormAdminLaporan.setFocusPainted(false);
        btnProfilFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfilFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 40));

        btnBerandaFormAdminLaporan.setForeground(java.awt.Color.white);
        btnBerandaFormAdminLaporan.setText("Beranda");
        btnBerandaFormAdminLaporan.setBorderPainted(false);
        btnBerandaFormAdminLaporan.setContentAreaFilled(false);
        btnBerandaFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBerandaFormAdminLaporan.setFocusPainted(false);
        btnBerandaFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnBerandaFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 47, -1, -1));

        btnKelolaDataFormAdminLaporan.setForeground(java.awt.Color.white);
        btnKelolaDataFormAdminLaporan.setText("Kelola Data");
        btnKelolaDataFormAdminLaporan.setBorderPainted(false);
        btnKelolaDataFormAdminLaporan.setContentAreaFilled(false);
        btnKelolaDataFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDataFormAdminLaporan.setFocusPainted(false);
        btnKelolaDataFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDataFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnKelolaDataFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, -1));

        btnKelolaDestinasiFormAdminLaporan.setForeground(java.awt.Color.white);
        btnKelolaDestinasiFormAdminLaporan.setText("Kelola Destinasi");
        btnKelolaDestinasiFormAdminLaporan.setBorderPainted(false);
        btnKelolaDestinasiFormAdminLaporan.setContentAreaFilled(false);
        btnKelolaDestinasiFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDestinasiFormAdminLaporan.setFocusPainted(false);
        btnKelolaDestinasiFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDestinasiFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnKelolaDestinasiFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 112, -1, -1));

        btnLaporanFormAdminLaporan.setForeground(java.awt.Color.white);
        btnLaporanFormAdminLaporan.setText("Laporan");
        btnLaporanFormAdminLaporan.setBorderPainted(false);
        btnLaporanFormAdminLaporan.setContentAreaFilled(false);
        btnLaporanFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanFormAdminLaporan.setFocusPainted(false);
        btnLaporanFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporanFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 146, -1, -1));

        btnKeluarFormAdminLaporan.setForeground(java.awt.Color.white);
        btnKeluarFormAdminLaporan.setText("Keluar");
        btnKeluarFormAdminLaporan.setBorderPainted(false);
        btnKeluarFormAdminLaporan.setContentAreaFilled(false);
        btnKeluarFormAdminLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluarFormAdminLaporan.setFocusPainted(false);
        btnKeluarFormAdminLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarFormAdminLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluarFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 360, -1, -1));

        tableLaporanFormAdminLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Tanggal", "Status", "Opsi"
            }
        ));
        scrollPaneTableLaporanFormAdminLaporan.setViewportView(tableLaporanFormAdminLaporan);

        getContentPane().add(scrollPaneTableLaporanFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 440, 300));

        bgFormAdminLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan Dashboard Admin Laporan.png"))); // NOI18N
        getContentPane().add(bgFormAdminLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaDestinasiFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDestinasiFormAdminLaporanActionPerformed
        new FormAdminKelolaDestinasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaDestinasiFormAdminLaporanActionPerformed

    private void btnBerandaFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaFormAdminLaporanActionPerformed
        new FormAdminBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBerandaFormAdminLaporanActionPerformed

    private void btnKelolaDataFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDataFormAdminLaporanActionPerformed
        new FormAdminKelolaData().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaDataFormAdminLaporanActionPerformed

    private void btnLaporanFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanFormAdminLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanFormAdminLaporanActionPerformed

    private void btnKeluarFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarFormAdminLaporanActionPerformed
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarFormAdminLaporanActionPerformed

    private void btnProfilFormAdminLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilFormAdminLaporanActionPerformed
        new FormAdminAkun().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProfilFormAdminLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormAdminLaporan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgFormAdminLaporan;
    private javax.swing.JButton btnBerandaFormAdminLaporan;
    private javax.swing.JButton btnKelolaDataFormAdminLaporan;
    private javax.swing.JButton btnKelolaDestinasiFormAdminLaporan;
    private javax.swing.JButton btnKeluarFormAdminLaporan;
    private javax.swing.JButton btnLaporanFormAdminLaporan;
    private javax.swing.JButton btnProfilFormAdminLaporan;
    private javax.swing.JScrollPane scrollPaneTableLaporanFormAdminLaporan;
    private javax.swing.JTable tableLaporanFormAdminLaporan;
    // End of variables declaration//GEN-END:variables
}
