import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Form untuk mengelola data pengguna dalam aplikasi Tripnesia.
 * Form ini memungkinkan admin untuk melihat, menambah, mengubah, dan menghapus
 * data pengguna yang terdaftar dalam sistem.
 * 
 * @author tim F.N.M Trip
 */
public class FormAdminKelolaData extends javax.swing.JFrame {

    /**
     * Konstruktor untuk membuat form kelola data pengguna baru.
     * Menginisialisasi komponen GUI dan memuat data pengguna dari database.
     */
    public FormAdminKelolaData() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        // Memuat dan menampilkan data pengguna dari database ke tabel
        muatDataUser();
    }
    
    /**
     * Memuat data pengguna dari database dan menampilkannya di tabel.
     * Mengambil data nama, email, nomor telepon, dan jenis kelamin pengguna
     * dari tabel 'users' dan menampilkannya dalam JTable.
     * 
     * 
     */
    private void muatDataUser() {
        DefaultTableModel model = (DefaultTableModel) tableKelolaDataFormAdminKelolaData.getModel();
        model.setRowCount(0); // Menghapus semua baris yang ada di tabel sebelum memuat data baru

        try (Connection conn = Koneksi.getConnection();
             PreparedStatement pst = conn.prepareStatement("SELECT nama, email, nomor, jeniskelamin FROM users");
             ResultSet rs = pst.executeQuery()) {

            // Melakukan pengulangan melalui semua hasil query
            while (rs.next()) {
                // Menambahkan setiap baris data ke model tabel
                model.addRow(new Object[]{
                    rs.getString("nama"),           // Kolom 1: Nama pengguna
                    rs.getString("email"),          // Kolom 2: Email pengguna
                    rs.getString("nomor"),          // Kolom 3: Nomor telepon pengguna
                    rs.getString("jeniskelamin")    // Kolom 4: Jenis kelamin pengguna
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfilFormAdminKelolaData = new javax.swing.JButton();
        btnBerandaFormAdminKelolaData = new javax.swing.JButton();
        btnKelolaDataFormAdminKelolaData = new javax.swing.JButton();
        btnKelolaDestinasiFormAdminKelolaData = new javax.swing.JButton();
        btnLaporanFormAdminKelolaData = new javax.swing.JButton();
        btnKeluarFormAdminKelolaData = new javax.swing.JButton();
        scrollPaneTableKelolaDataFormAdminKelolaData = new javax.swing.JScrollPane();
        tableKelolaDataFormAdminKelolaData = new javax.swing.JTable();
        bgFormAdminKelolaData = new javax.swing.JLabel();

        setTitle("Tripnesia - Dashboard Admin - Kelola Data");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfilFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnProfilFormAdminKelolaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profil icon.png"))); // NOI18N
        btnProfilFormAdminKelolaData.setBorderPainted(false);
        btnProfilFormAdminKelolaData.setContentAreaFilled(false);
        btnProfilFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfilFormAdminKelolaData.setFocusPainted(false);
        btnProfilFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfilFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 40));

        btnBerandaFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnBerandaFormAdminKelolaData.setText("Beranda");
        btnBerandaFormAdminKelolaData.setBorderPainted(false);
        btnBerandaFormAdminKelolaData.setContentAreaFilled(false);
        btnBerandaFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBerandaFormAdminKelolaData.setFocusPainted(false);
        btnBerandaFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnBerandaFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 47, -1, -1));

        btnKelolaDataFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnKelolaDataFormAdminKelolaData.setText("Kelola Data");
        btnKelolaDataFormAdminKelolaData.setBorderPainted(false);
        btnKelolaDataFormAdminKelolaData.setContentAreaFilled(false);
        btnKelolaDataFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDataFormAdminKelolaData.setFocusPainted(false);
        btnKelolaDataFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDataFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnKelolaDataFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, -1));

        btnKelolaDestinasiFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnKelolaDestinasiFormAdminKelolaData.setText("Kelola Destinasi");
        btnKelolaDestinasiFormAdminKelolaData.setBorderPainted(false);
        btnKelolaDestinasiFormAdminKelolaData.setContentAreaFilled(false);
        btnKelolaDestinasiFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDestinasiFormAdminKelolaData.setFocusPainted(false);
        btnKelolaDestinasiFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDestinasiFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnKelolaDestinasiFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 112, -1, -1));

        btnLaporanFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnLaporanFormAdminKelolaData.setText("Laporan");
        btnLaporanFormAdminKelolaData.setBorderPainted(false);
        btnLaporanFormAdminKelolaData.setContentAreaFilled(false);
        btnLaporanFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanFormAdminKelolaData.setFocusPainted(false);
        btnLaporanFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporanFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 146, -1, -1));

        btnKeluarFormAdminKelolaData.setForeground(java.awt.Color.white);
        btnKeluarFormAdminKelolaData.setText("Keluar");
        btnKeluarFormAdminKelolaData.setBorderPainted(false);
        btnKeluarFormAdminKelolaData.setContentAreaFilled(false);
        btnKeluarFormAdminKelolaData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluarFormAdminKelolaData.setFocusPainted(false);
        btnKeluarFormAdminKelolaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarFormAdminKelolaDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluarFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 360, -1, -1));

        tableKelolaDataFormAdminKelolaData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Email", "Nomor Telepon", "Jenis Kelamin"
            }
        ));
        scrollPaneTableKelolaDataFormAdminKelolaData.setViewportView(tableKelolaDataFormAdminKelolaData);

        getContentPane().add(scrollPaneTableKelolaDataFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 440, 300));

        bgFormAdminKelolaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan Dashboard Admin Kelola Data.png"))); // NOI18N
        getContentPane().add(bgFormAdminKelolaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaFormAdminKelolaDataActionPerformed
        new FormAdminBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBerandaFormAdminKelolaDataActionPerformed

    private void btnKelolaDataFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDataFormAdminKelolaDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaDataFormAdminKelolaDataActionPerformed

    private void btnKelolaDestinasiFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDestinasiFormAdminKelolaDataActionPerformed
        new FormAdminKelolaDestinasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaDestinasiFormAdminKelolaDataActionPerformed

    private void btnLaporanFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanFormAdminKelolaDataActionPerformed
        new FormAdminLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLaporanFormAdminKelolaDataActionPerformed

    private void btnKeluarFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarFormAdminKelolaDataActionPerformed
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarFormAdminKelolaDataActionPerformed

    private void btnProfilFormAdminKelolaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilFormAdminKelolaDataActionPerformed
        new FormAdminAkun().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProfilFormAdminKelolaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdminKelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdminKelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdminKelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdminKelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormAdminKelolaData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgFormAdminKelolaData;
    private javax.swing.JButton btnBerandaFormAdminKelolaData;
    private javax.swing.JButton btnKelolaDataFormAdminKelolaData;
    private javax.swing.JButton btnKelolaDestinasiFormAdminKelolaData;
    private javax.swing.JButton btnKeluarFormAdminKelolaData;
    private javax.swing.JButton btnLaporanFormAdminKelolaData;
    private javax.swing.JButton btnProfilFormAdminKelolaData;
    private javax.swing.JScrollPane scrollPaneTableKelolaDataFormAdminKelolaData;
    private javax.swing.JTable tableKelolaDataFormAdminKelolaData;
    // End of variables declaration//GEN-END:variables
}
