import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Form untuk menambahkan destinasi wisata baru dalam sistem admin Tripnesia.
 * Form ini menyediakan interface untuk memasukkan informasi lengkap destinasi
 * termasuk nama, alamat, deskripsi, harga, jam operasional, kategori, dan gambar.
 * 
 * @author tim F.N.M Trip
 */
public class FormAdminTambahDestinasi extends javax.swing.JFrame {

    /**
     * File gambar yang dipilih oleh admin untuk destinasi.
     * Digunakan untuk menyimpan referensi file gambar sebelum diupload ke database.
     */
    private File fileGambar = null;

    /**
     * Konstruktor untuk membuat form tambah destinasi baru.
     * Menginisialisasi komponen GUI dan mengatur properti window.
     */
    public FormAdminTambahDestinasi() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnProfilFormAdminTambahDestinasi = new javax.swing.JButton();
        btnBerandaFormAdminTambahDestinasi = new javax.swing.JButton();
        btnKelolaDataFormAdminTambahDestinasi = new javax.swing.JButton();
        btnLoginSignUp5 = new javax.swing.JButton();
        btnLoginSignUp4 = new javax.swing.JButton();
        btnLoginSignUp6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        lblPreview = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bgFormAdminTambahDestinasi = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jFormattedTextField1.setText("jFormattedTextField1");

        setTitle("Tripnesia - Dashboard Admin - Tambah Destinasi");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfilFormAdminTambahDestinasi.setForeground(java.awt.Color.white);
        btnProfilFormAdminTambahDestinasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profil icon.png"))); // NOI18N
        btnProfilFormAdminTambahDestinasi.setBorderPainted(false);
        btnProfilFormAdminTambahDestinasi.setContentAreaFilled(false);
        btnProfilFormAdminTambahDestinasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfilFormAdminTambahDestinasi.setFocusPainted(false);
        btnProfilFormAdminTambahDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilFormAdminTambahDestinasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfilFormAdminTambahDestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 40));

        btnBerandaFormAdminTambahDestinasi.setForeground(java.awt.Color.white);
        btnBerandaFormAdminTambahDestinasi.setText("Beranda");
        btnBerandaFormAdminTambahDestinasi.setBorderPainted(false);
        btnBerandaFormAdminTambahDestinasi.setContentAreaFilled(false);
        btnBerandaFormAdminTambahDestinasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBerandaFormAdminTambahDestinasi.setFocusPainted(false);
        btnBerandaFormAdminTambahDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaFormAdminTambahDestinasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnBerandaFormAdminTambahDestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 47, -1, -1));

        btnKelolaDataFormAdminTambahDestinasi.setForeground(java.awt.Color.white);
        btnKelolaDataFormAdminTambahDestinasi.setText("Kelola Data");
        btnKelolaDataFormAdminTambahDestinasi.setBorderPainted(false);
        btnKelolaDataFormAdminTambahDestinasi.setContentAreaFilled(false);
        btnKelolaDataFormAdminTambahDestinasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDataFormAdminTambahDestinasi.setFocusPainted(false);
        btnKelolaDataFormAdminTambahDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaDataFormAdminTambahDestinasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKelolaDataFormAdminTambahDestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, -1));

        btnLoginSignUp5.setForeground(java.awt.Color.white);
        btnLoginSignUp5.setText("Kelola Destinasi");
        btnLoginSignUp5.setBorderPainted(false);
        btnLoginSignUp5.setContentAreaFilled(false);
        btnLoginSignUp5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginSignUp5.setFocusPainted(false);
        btnLoginSignUp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSignUp5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginSignUp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 112, -1, -1));

        btnLoginSignUp4.setForeground(java.awt.Color.white);
        btnLoginSignUp4.setText("Laporan");
        btnLoginSignUp4.setBorderPainted(false);
        btnLoginSignUp4.setContentAreaFilled(false);
        btnLoginSignUp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginSignUp4.setFocusPainted(false);
        btnLoginSignUp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSignUp4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginSignUp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 146, -1, -1));

        btnLoginSignUp6.setForeground(java.awt.Color.white);
        btnLoginSignUp6.setText("Keluar");
        btnLoginSignUp6.setBorderPainted(false);
        btnLoginSignUp6.setContentAreaFilled(false);
        btnLoginSignUp6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginSignUp6.setFocusPainted(false);
        btnLoginSignUp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSignUp6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginSignUp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 360, -1, -1));

        jLabel2.setText("Nama Destinasi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        jLabel4.setText("Deskripsi Destinasi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 60));

        jLabel5.setText("Harga Destinasi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 170, -1));

        jLabel9.setText("Gambar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/picture icon.png"))); // NOI18N
        jButton1.setText("Pilih Foto");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 100, -1));

        jLabel3.setText("Kategori");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Destinasi Candi & Pura", "Destinasi Danau & Kepulauan", "Destinasi Gunung", "Destinasi Kawah", "Destinasi Pantai", "Destinasi Museum", "Destinasi Wisata Kota & Budaya", "Destinasi Wisata Alam & Satwa", "Destinasi Wisata Buatan (Taman Hiburan)" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 220, -1));

        jLabel10.setText("Alamat Destinasi");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 220, -1));

        jLabel6.setText("Jam Operasional");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 220, -1));
        getContentPane().add(lblPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 107, 73));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 100, -1));

        jButton3.setText("Tambah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 100, -1));

        bgFormAdminTambahDestinasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan Dashboard Admin Tambah Destinasi.png"))); // NOI18N
        getContentPane().add(bgFormAdminTambahDestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handler untuk tombol pilih gambar.
     * Membuka dialog file chooser untuk memilih gambar destinasi.
     * Mendukung format JPG, PNG, dan JPEG.
     * 
     * @param evt Event action yang dipicu oleh tombol
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "png", "jpeg");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            fileGambar = selectedFile;
            String path = selectedFile.getAbsolutePath();
            ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage().getScaledInstance(107, 73, Image.SCALE_SMOOTH);
            lblPreview.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FormAdminKelolaDestinasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * Handler untuk tombol Tambah destinasi.
     * Memvalidasi input, menyimpan gambar ke folder, dan menyimpan data ke database.
     * 
     * @param evt Event action yang dipicu oleh tombol
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        // Mengambil data dari form
        String nama = jTextField1.getText();
        String alamat = jTextField2.getText();
        String deskripsi = jTextArea1.getText();
        String harga = jTextField3.getText();
        String jamBuka = jTextField4.getText();
        String kategori = jComboBox2.getSelectedItem().toString();
        
        // Validasi: pastikan semua field terisi
        if (nama.isEmpty() || alamat.isEmpty() || deskripsi.isEmpty() || harga.isEmpty() || jamBuka.isEmpty() || fileGambar == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi dan gambar harus dipilih!");
            return;
        }
        
        // Validasi: pastikan kategori sudah dipilih
        if (kategori.equals("Pilih Kategori")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih kategori destinasi!");
            return;
        }

        try {
            Connection conn = Koneksi.getConnection();
            String namaFile = fileGambar.getName();
            // Membuat folder images jika belum ada
            File destFolder = new File("images");
            if (!destFolder.exists()) {
                destFolder.mkdirs(); // bikin folder kalo belum ada
            }
            File destFile = new File(destFolder, namaFile);

            // Menyalin file gambar ke folder images
            Files.copy(fileGambar.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Query SQL untuk insert data destinasi
            String sql = "INSERT INTO destinasi (nama, alamat, deskripsi, harga, jambuka, kategori ,gambar) VALUES (?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nama);
            stmt.setString(2, alamat);
            stmt.setString(3, deskripsi);
            stmt.setInt(4, Integer.parseInt(harga));
            stmt.setString(5, jamBuka);
            stmt.setString(6, kategori); 
            stmt.setString(7, namaFile);

            stmt.executeUpdate(); //Eksekusi query

            javax.swing.JOptionPane.showMessageDialog(this, "Destinasi berhasil ditambahkan!");

            // Reset form
            jTextField1.setText("");
            jTextField2.setText("");
            jTextArea1.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jComboBox2.setSelectedIndex(0);
            lblPreview.setIcon(null);
            fileGambar = null;

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan saat menyimpan data ke database:\n" + e.getMessage(),
                "SQL Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan saat menyimpan gambar:\n" + e.getMessage(),
                "File Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBerandaFormAdminTambahDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaFormAdminTambahDestinasiActionPerformed
        new FormAdminBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBerandaFormAdminTambahDestinasiActionPerformed

    private void btnKelolaDataFormAdminTambahDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaDataFormAdminTambahDestinasiActionPerformed
        new FormAdminKelolaData().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaDataFormAdminTambahDestinasiActionPerformed

    private void btnLoginSignUp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSignUp4ActionPerformed
        new FormAdminLaporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginSignUp4ActionPerformed

    private void btnLoginSignUp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSignUp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginSignUp5ActionPerformed

    private void btnLoginSignUp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSignUp6ActionPerformed
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginSignUp6ActionPerformed

    private void btnProfilFormAdminTambahDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilFormAdminTambahDestinasiActionPerformed
        new FormAdminAkun().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProfilFormAdminTambahDestinasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdminTambahDestinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdminTambahDestinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdminTambahDestinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdminTambahDestinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormAdminTambahDestinasi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgFormAdminTambahDestinasi;
    private javax.swing.JButton btnBerandaFormAdminTambahDestinasi;
    private javax.swing.JButton btnKelolaDataFormAdminTambahDestinasi;
    private javax.swing.JButton btnLoginSignUp4;
    private javax.swing.JButton btnLoginSignUp5;
    private javax.swing.JButton btnLoginSignUp6;
    private javax.swing.JButton btnProfilFormAdminTambahDestinasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblPreview;
    // End of variables declaration//GEN-END:variables
}
