/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class FrameBeranda extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameBeranda
     */
    
    public FrameBeranda() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            FramePembelianTiket pembelian = new FramePembelianTiket(1); // Candi Borobudur
            pembelian.setVisible(true);
            dispose();
        }
    });

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FramePembelianTiket pembelian = new FramePembelianTiket(14); // Labuan Bajo
                pembelian.setVisible(true);
                dispose();
            }
        });

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FramePembelianTiket pembelian = new FramePembelianTiket(17); // Danau Toba
                pembelian.setVisible(true);
                dispose();
            }
        });
    }

private void bukaFramePemesanan(String nama, int harga, String jamBuka, String deskripsi, String gambarPath) {
        FramePembelianTiket pembelian = new FramePembelianTiket(1); // 1 adalah id_destinasi dari Borobudur
        pembelian.setVisible(true);
        this.dispose(); // kalau mau nutup frame beranda

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        akunProfilKeluar = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripnesia - Beranda User");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        akunProfilKeluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akun", "Profil", "Keluar" }));
        akunProfilKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunProfilKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(akunProfilKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 22, -1, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Destinasi Candi & Pura", "Destinasi Danau & Kepulauan", "Destinasi Gunung", "Destinasi Kawah", "Destinasi Pantai", "Destinasi Museum", "Destinasi Wisata Kota & Budaya", "Destinasi Wisata Alam & Satwa", "Destinasi Wisata Buatan (Taman Hiburan)" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(72, 24));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 73, 167, 28));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Beranda");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 100, 30));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(null);

        jLabel16.setBackground(new java.awt.Color(255, 153, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Paling Favorit");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        jLabel16.setOpaque(true);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 90, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/labuan bj.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 120, 80);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Labuan Bajo");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 90, 90, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText(" Surga Favorit Traveler!");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 100, 140, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        jLabel13.setText("<html> Destinasi eksotis di ujung barat Flores<br> \nyang jadi pintu masuk ke Taman Nasional Komodo. <br> \nNikmati sailing trip, snorkeling di laut sebening kristal,<br> \ndan pemandangan sunset yang bikin lupa pulang.\n </html>\n");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 120, 140, 50);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 180));

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 153, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Paling Laris");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 80, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/candi brbdr.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 120, 80);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(" Candi Borobudur");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 120, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Destinasi Paling Diburu!");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 100, 140, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        jLabel7.setText("<html> Candi Buddha terbesar di dunia yang<br> terletak di Magelang, Jawa Tengah.<br> Borobudur terkenal dengan arsitektur yang megah<br> dan panorama matahari terbit yang menakjubkan. </html>");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 120, 140, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 180));

        jPanel4.setBackground(new java.awt.Color(229, 229, 229));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(255, 153, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Paling Banyak Dicari");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        jLabel15.setOpaque(true);
        jPanel4.add(jLabel15);
        jLabel15.setBounds(0, 0, 100, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dnu tb.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 80);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Danau Toba");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 90, 100, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setText(" Primadona Pencarian Online!");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 100, 140, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel14.setText("<html> Tenang, sejuk, dan<br>\n dan luas tak bertepi—Danau Toba.<br> \nselalu jadi pilihan utama buat <br>\nliburan santai dan eksplorasi budaya.\n </html>");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, 120, 140, 50);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 140, 180));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/currency_exchange_27dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton5.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 23, 40, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BG Tampilan User FINAL FINAL FINAL.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new FrameBeranda().setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void akunProfilKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunProfilKeluarActionPerformed
        // TODO add your handling code here:
    String pilihan = akunProfilKeluar.getSelectedItem().toString();

    if (pilihan.equals("Profil")) {
        new FrameProfilUser().setVisible(true);
        dispose();
    } else if (pilihan.equals("Keluar")) {
        new FormLogin().setVisible(true);
        dispose();
    }

    // Kembalikan ke "Akun"
    akunProfilKeluar.setSelectedIndex(0);


    
    }//GEN-LAST:event_akunProfilKeluarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new FrameStatusPemesanan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String kategoriDipilih = jComboBox2.getSelectedItem().toString();
        if(kategoriDipilih.equals("Destinasi Candi & Pura")){
            new FrameKategoriCandiPura().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Danau & Kepulauan")){
            new FrameKategoriDanauPulau().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Gunung")){
            new FrameKategoriGunung().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Kawah")){
            new FrameKategoriKawah().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Pantai")){
            new FrameKategoriPantai().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Museum")){
            new FrameKategoriMuseum().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Kota & Budaya")){
            new FrameKategoriWisataKotaBudaya().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Alam & Satwa")){
            new FrameKategoriWisataAlamSatwa().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Buatan (Taman Hiburan)")){
            new FrameKategoriWisataBuatan().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameBeranda().setVisible(true);
        });
    }
        
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akunProfilKeluar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
