/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Kelas FrameTiket adalah GUI untuk menampilkan tiket wisata yang telah disetujui.
 * Frame ini berfungsi sebagai e-ticket yang dapat diunduh dan ditampilkan kepada user
 * setelah pemesanan mereka disetujui oleh admin.
 * 
 * Fitur utama:
 * - Menampilkan QR Code untuk verifikasi tiket
 * - Tombol navigasi kembali ke beranda
 * - Desain tiket yang profesional dengan background khusus
 * 
 * @author tim F.N.M Trip
 */
public class FrameTiket extends javax.swing.JFrame {

    /**
     * Konstruktor default untuk membuat instance FrameTiket kosong.
     * 
     */
    public FrameTiket() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }
    
    /**
     * Konstruktor utama untuk membuat instance FrameTiket dengan data pemesanan.
     * Konstruktor ini akan mengisi semua field tiket dengan data yang diberikan.
     * 
     * @param namaDestinasi Nama destinasi wisata yang dipesan
     * @param namaPemesan Nama lengkap pemesan tiket
     * @param tanggal Tanggal pemesanan tiket
     * @param jumlahTiket Jumlah PAX (penumpang/orang) yang dipesan
     */
    public FrameTiket(String namaDestinasi, String namaPemesan, String tanggal, int jumlahTiket) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        // Mengisi data tiket dengan informasi pemesanan
        this.namadestinasi.setText(namaDestinasi);
        this.namapemesan.setText(namaPemesan);
        this.tanggalPesan.setText(tanggal);
        this.jumlahpesantiket.setText(String.valueOf(jumlahTiket));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namadestinasi = new javax.swing.JLabel();
        jumlahpesantiket = new javax.swing.JTextField();
        jamdestinasi = new javax.swing.JTextField();
        tanggalPesan = new javax.swing.JTextField();
        namapemesan = new javax.swing.JTextField();
        btnHomepg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripnesia - Tiket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Orang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Jumlah PAX");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        namadestinasi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        namadestinasi.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(namadestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jumlahpesantiket.setEditable(false);
        jumlahpesantiket.setBackground(new java.awt.Color(255, 255, 255));
        jumlahpesantiket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jumlahpesantiket.setBorder(null);
        getContentPane().add(jumlahpesantiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 20));

        jamdestinasi.setEditable(false);
        jamdestinasi.setBackground(new java.awt.Color(255, 255, 255));
        jamdestinasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jamdestinasi.setBorder(null);
        getContentPane().add(jamdestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 120, 20));

        tanggalPesan.setEditable(false);
        tanggalPesan.setBackground(new java.awt.Color(255, 255, 255));
        tanggalPesan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tanggalPesan.setBorder(null);
        tanggalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalPesanActionPerformed(evt);
            }
        });
        getContentPane().add(tanggalPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 20));

        namapemesan.setEditable(false);
        namapemesan.setBackground(new java.awt.Color(255, 255, 255));
        namapemesan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namapemesan.setBorder(null);
        namapemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapemesanActionPerformed(evt);
            }
        });
        getContentPane().add(namapemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, 20));

        btnHomepg.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnHomepg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnHomepg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        btnHomepg.setBorderPainted(false);
        btnHomepg.setContentAreaFilled(false);
        btnHomepg.setFocusable(false);
        btnHomepg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnHomepg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomepgActionPerformed(evt);
            }
        });
        getContentPane().add(btnHomepg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan Tiket User FINAL FINAL FINAL FINAL.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namapemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapemesanActionPerformed

    private void tanggalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalPesanActionPerformed

    private void btnHomepgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomepgActionPerformed
        // TODO add your handling code here:
        new FrameBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomepgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomepg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jamdestinasi;
    private javax.swing.JTextField jumlahpesantiket;
    private javax.swing.JLabel namadestinasi;
    private javax.swing.JTextField namapemesan;
    private javax.swing.JTextField tanggalPesan;
    // End of variables declaration//GEN-END:variables
}
