
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Kelas ini digunakan untuk menangani proses pembayaran tiket wisata.
 * Form ini memungkinkan pengguna untuk mengisi data pemesan, memilih metode pembayaran,
 * dan melihat ringkasan pemesanan sebelum melakukan pembayaran.
 * 
 * Fitur utama:
 * - Input data pemesan (nama, jenis kelamin, nomor telepon, email)
 * - Pemilihan metode pembayaran (bank, e-wallet, minimarket)
 * - Tampilan ringkasan pemesanan dengan gambar destinasi
 * - Validasi input sebelum proses pembayaran
 * 
 * @author F.N.M Trip
 */
public class FramePembayaranTiket extends javax.swing.JFrame {

    /**
     * Konstruktor default untuk membuat form pembayaran tiket baru.
     * Menginisialisasi komponen, mengatur properti frame, dan mengelompokkan radio button.
     */
    public FramePembayaranTiket() {
        initComponents();
        setResizable(false); // Agar frame tidak bisa diubah ukurannya
        setLocationRelativeTo(null); // Agar Posisi frame di tengah layar
        groupRadioButtons(); // Mengelompokkan radio button untuk gender dan payment

    }
    
    /**
     * Konstruktor dengan parameter untuk membuat form pembayaran dengan data pemesanan
     * Konstruktor ini digunakan ketika form dipanggil dari form pembelian tiket
     * 
     * @param namaDestinasi
     * @param gambar
     * @param tglKunjungan
     * @param jumlah
     * @param totalHarga 
     */
    public FramePembayaranTiket(String namaDestinasi, String gambar, String tglKunjungan, int jumlah, int totalHarga) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        groupRadioButtons();

        // Atur isi komponen sesuai data dari pembelian
        lblGambar.setIcon(new ImageIcon(getClass().getResource("/resources/Foto Destinasi/" + gambar)));
        tglKunjunganUser.setText(tglKunjungan);
        jmlTiketUser.setText(jumlah + " tiket");
        jumlahTiket.setText(String.valueOf(jumlah));

        String totalFormatted = String.format("Rp %,d", totalHarga).replace(",", ".") + ",00";
        updateTotal.setText(totalFormatted);

        // Mengelompokkan radio button untuk jenis kelamin
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(lakiLaki);
        genderGroup.add(peremPuan);

        // Mengelompokkan radio button untuk metode pembayaran
        ButtonGroup paymentGroup = new ButtonGroup();
        paymentGroup.add(paymentBCA);
        paymentGroup.add(paymentBNI);
        paymentGroup.add(paymentBRI);
        paymentGroup.add(paymentMandiri);
        paymentGroup.add(PaymentOVO);
        paymentGroup.add(paymentDana);
        paymentGroup.add(paymentQris);
        paymentGroup.add(paymentIndomaret);
        paymentGroup.add(paymentAlfamart);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peremPuan = new javax.swing.JRadioButton();
        lakiLaki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        inputNoTelp = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updateTotal = new javax.swing.JLabel();
        jumlahTiket = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jmlTiketUser = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tglKunjunganUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        paymentBCA = new javax.swing.JRadioButton();
        paymentBNI = new javax.swing.JRadioButton();
        paymentBRI = new javax.swing.JRadioButton();
        paymentMandiri = new javax.swing.JRadioButton();
        PaymentOVO = new javax.swing.JRadioButton();
        paymentDana = new javax.swing.JRadioButton();
        paymentQris = new javax.swing.JRadioButton();
        paymentIndomaret = new javax.swing.JRadioButton();
        paymentAlfamart = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripnesia - Pembayaran Tiket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peremPuan.setBackground(java.awt.Color.white);
        peremPuan.setText("Perempuan");
        peremPuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peremPuanActionPerformed(evt);
            }
        });
        getContentPane().add(peremPuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        lakiLaki.setBackground(java.awt.Color.white);
        lakiLaki.setText("Laki - Laki");
        lakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiActionPerformed(evt);
            }
        });
        getContentPane().add(lakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nomor Handphone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        inputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        getContentPane().add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, -1));

        inputNoTelp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        getContentPane().add(inputNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        namaLengkap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 350, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nama Lengkap");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Ringkasan Pemesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Data Pemesan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 66, 130, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Harga yang Anda bayar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("PAX");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        updateTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateTotal.setForeground(new java.awt.Color(255, 153, 51));
        updateTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(updateTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 140, 20));

        jumlahTiket.setEditable(false);
        jumlahTiket.setBackground(java.awt.Color.white);
        jumlahTiket.setForeground(new java.awt.Color(102, 102, 102));
        jumlahTiket.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahTiket.setBorder(null);
        getContentPane().add(jumlahTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 290, 20, -1));

        jLabel11.setBackground(new java.awt.Color(255, 153, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html>\nPilih Metode<br>\nPembayaran\n<html>");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, 40));

        lblGambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Jumlah");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jmlTiketUser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jmlTiketUser.setForeground(new java.awt.Color(102, 102, 102));
        jmlTiketUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jmlTiketUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tanggal Kunjungan");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tglKunjunganUser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tglKunjunganUser.setForeground(new java.awt.Color(102, 102, 102));
        tglKunjunganUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(tglKunjunganUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 60, 10));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, 20));

        paymentBCA.setBackground(new java.awt.Color(255, 255, 255));
        paymentBCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBCAActionPerformed(evt);
            }
        });
        getContentPane().add(paymentBCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        paymentBNI.setBackground(java.awt.Color.white);
        getContentPane().add(paymentBNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        paymentBRI.setBackground(java.awt.Color.white);
        getContentPane().add(paymentBRI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        paymentMandiri.setBackground(java.awt.Color.white);
        paymentMandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMandiriActionPerformed(evt);
            }
        });
        getContentPane().add(paymentMandiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        PaymentOVO.setBackground(java.awt.Color.white);
        getContentPane().add(PaymentOVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        paymentDana.setBackground(java.awt.Color.white);
        getContentPane().add(paymentDana, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        paymentQris.setBackground(java.awt.Color.white);
        getContentPane().add(paymentQris, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        paymentIndomaret.setBackground(java.awt.Color.white);
        getContentPane().add(paymentIndomaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        paymentAlfamart.setBackground(java.awt.Color.white);
        getContentPane().add(paymentAlfamart, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bri.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 70, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dana.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 70, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bni.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 70, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bca.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 70, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alfamart.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 70, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ovo.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 70, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mandiri.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/qris.jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 70, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/indomaret.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan Pembayaran Tiket User.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void peremPuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peremPuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peremPuanActionPerformed

    private void paymentMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMandiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMandiriActionPerformed

    /**
     * Metode untuk mengelompokkan radio button ke dalam ButtonGroup.
     * Metode ini memastikan bahwa hanya satu pilihan yang bisa dipilih dalam setiap grup.
     * 
     * Grup yang dibuat:
     * - genderGroup: untuk pilihan jenis kelamin (Laki-laki/Perempuan)
     * - paymentGroup: untuk pilihan metode pembayaran (9 pilihan metode)
     */
    private void groupRadioButtons() {
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(lakiLaki);
        genderGroup.add(peremPuan);

        ButtonGroup paymentGroup = new ButtonGroup();
        paymentGroup.add(paymentBCA);
        paymentGroup.add(paymentBNI);
        paymentGroup.add(paymentBRI);
        paymentGroup.add(paymentMandiri);
        paymentGroup.add(PaymentOVO);
        paymentGroup.add(paymentDana);
        paymentGroup.add(paymentQris);
        paymentGroup.add(paymentIndomaret);
        paymentGroup.add(paymentAlfamart);
    }
    
    /**
     * Metode untuk mendapatkan metode pembayaran yang dipilih pengguna.
     * Metode ini mengecek semua radio button pembayaran dan mengembalikan string
     * yang sesuai dengan pilihan yang dipilih.
     * 
     * @return String nama metode pembayaran yang dipilih, atau null jika tidak ada yang dipilih
     */
    private String getMetodePembayaranDipilih() {
        if (paymentBCA.isSelected()) return "BCA";
        if (paymentBNI.isSelected()) return "BNI";
        if (paymentBRI.isSelected()) return "BRI";
        if (paymentMandiri.isSelected()) return "Mandiri";
        if (PaymentOVO.isSelected()) return "OVO";
        if (paymentDana.isSelected()) return "Dana";
        if (paymentQris.isSelected()) return "qris";
        if (paymentIndomaret.isSelected()) return "Indomaret";
        if (paymentAlfamart.isSelected()) return "Alfamart";
        return null;
    }

    
    /**
     * Event handler untuk tombol "Bayar".
     * Metode ini melakukan validasi input pengguna sebelum memproses pembayaran.
     * Jika semua input valid, akan membuka form bukti bayar dan menutup form ini.
     * 
     * Validasi yang dilakukan:
     * 1. Memastikan jenis kelamin sudah dipilih
     * 2. Memastikan metode pembayaran sudah dipilih
     * 
     * @param evt Event yang dipicu ketika tombol bayar diklik
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Mengecek apakah jenis kelamin sudah dipilih
        if (!lakiLaki.isSelected() && !peremPuan.isSelected()) {
            JOptionPane.showMessageDialog(this, "Pilih jenis kelamin terlebih dahulu.");
            return; //keluar dari metode jika validasi gagal
        }
    
        //Mengecek apakah metode pembayaran sudah dipilih
        if (!(paymentBCA.isSelected() || paymentBNI.isSelected() || paymentBRI.isSelected()
            || paymentMandiri.isSelected() || PaymentOVO.isSelected() || paymentDana.isSelected()
            || paymentQris.isSelected() || paymentIndomaret.isSelected() || paymentAlfamart.isSelected())) {
            JOptionPane.showMessageDialog(this, "Pilih metode pembayaran terlebih dahulu.");
            return; //keluar dari metode jika validasi gagal
        }

        // Mengambil data dari komponen form
        String nama = namaLengkap.getText();
        String gender = lakiLaki.isSelected() ? "Laki-laki" : "Perempuan";
        String noTelp = inputNoTelp.getText();
        String email = inputEmail.getText();
        String metode = getMetodePembayaranDipilih();

        int idUser = 1;
        int idDestinasi = 1;
        int idPemesanan = 1;

        try {
            // Konek ke database
            Connection conn = Koneksi.getConnection(); 
            
            // Query buat insert data pembayaran
            String sql = "INSERT INTO pembayaran (id_user, id_destinasi, id_pemesanan, namalengkap, jeniskelamin, nohandphone, email) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idUser);
            pst.setInt(2, idDestinasi);
            pst.setInt(3, idPemesanan);
            pst.setString(4, nama);
            pst.setString(5, gender);
            pst.setString(6, noTelp);
            pst.setString(7, email);
            pst.executeUpdate(); // Eksekusi query

            JOptionPane.showMessageDialog(this, "Pembayaran berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            FrameStatusPemesanan statusPemesanan = new FrameStatusPemesanan();
            statusPemesanan.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan pembayaran!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void paymentBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentBCAActionPerformed

    private void lakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePembayaranTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePembayaranTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePembayaranTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePembayaranTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePembayaranTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton PaymentOVO;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jmlTiketUser;
    private javax.swing.JTextField jumlahTiket;
    private javax.swing.JRadioButton lakiLaki;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JRadioButton paymentAlfamart;
    private javax.swing.JRadioButton paymentBCA;
    private javax.swing.JRadioButton paymentBNI;
    private javax.swing.JRadioButton paymentBRI;
    private javax.swing.JRadioButton paymentDana;
    private javax.swing.JRadioButton paymentIndomaret;
    private javax.swing.JRadioButton paymentMandiri;
    private javax.swing.JRadioButton paymentQris;
    private javax.swing.JRadioButton peremPuan;
    private javax.swing.JLabel tglKunjunganUser;
    private javax.swing.JLabel updateTotal;
    // End of variables declaration//GEN-END:variables
}
