
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * kelas untuk tampilan halaman profil pengguna
 * Halaman ini digunakan untuk menampilkan dan mengubah informasi profil pengguna
 * seperti nama, email, nomor ponsel, dan kata sandi.
 * 
 * @author tim F.N.M Trip
 */
public class FrameProfilUser extends javax.swing.JFrame {

    /**
     * Konstruktor untuk membuat instance baru FrameProfilUser.
     * Method ini mengatur lokasi frame agar di tengah layar dan
     * membuat comboBox kategori transparan.
     */
    public FrameProfilUser() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        loadDataUser();
    }
    
    private void loadDataUser() {
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM users WHERE id_user = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Session.id_user); // ambil dari session
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                inputNama.setText(rs.getString("nama"));
                inputEmail.setText(rs.getString("email"));
                inputNomorPonsel.setText(rs.getString("nomor"));
                inputKataSandi.setText(rs.getString("password"));
                konfrKataSandi.setText(rs.getString("password"));
            }

            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data profil: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        inputNama = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputNomorPonsel = new javax.swing.JTextField();
        inputKataSandi = new javax.swing.JTextField();
        konfrKataSandi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tripnesia - Profil User");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Profil Saya");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Kelola informasi profil Anda untuk mengontrol, melindungi dan mengamankan akun ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, -1));
        getContentPane().add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        inputNomorPonsel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(inputNomorPonsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 160, -1));
        getContentPane().add(inputKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, -1));
        getContentPane().add(konfrKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Konfirmasi Kata Sandi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Kata Sandi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nomor Ponsel");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nama");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 20));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Beranda");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 100, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/currency_exchange_27dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton6.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 23, 40, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akun", "Profil", "Keluar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 22, -1, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Destinasi Candi & Pura", "Destinasi Danau & Kepulauan", "Destinasi Gunung", "Destinasi Kawah", "Destinasi Pantai", "Destinasi Museum", "Destinasi Wisata Kota & Budaya", "Destinasi Wisata Alam & Satwa", "Destinasi Wisata Buatan (Taman Hiburan)" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(72, 24));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 73, 167, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tampilan User profil FINAL BANGET.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    /**
     * Handler saat tombol Beranda ditekan.
     * Navigasi kembali ke FrameBeranda dan menutup frame ini.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new FrameBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Handler saat tombol Ubah ditekan.
     * Memeriksa semua field input, memastikan kata sandi dan konfirmasi cocok,
     * lalu memperbarui data pengguna di database.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //ambil data dari form
        String nama = inputNama.getText();
        String email = inputEmail.getText();
        String noPonsel = inputNomorPonsel.getText();
        String password = inputKataSandi.getText();
        String konfirmasi = konfrKataSandi.getText();

        //validasi, semua field harus diisi
        if (nama.isEmpty() || email.isEmpty() || noPonsel.isEmpty() || password.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seluruh field harus diisi!");
            return;
        }

        //validasi, password dan konfirmasi cocok
        if (!password.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Konfirmasi kata sandi tidak cocok!");
            return;
        }

        //Proses update data ke database
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "UPDATE users SET nama = ?, email = ?, nomor = ?, password = ? WHERE id_user = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setString(2, email);
            ps.setString(3, noPonsel);
            ps.setString(4, password);
            ps.setInt(5, Session.id_user);

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Profil berhasil diperbarui!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui profil.");
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat update data: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * Event handler untuk tombol Batal.
     * Membatalkan perubahan dan kembali ke halaman beranda.
     * 
     * @param evt Event yang dipicu saat tombol Batal diklik
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new FrameBeranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Event handler untuk combo box menu akun.
     * Menangani navigasi menu akun (Profil, Keluar).
     * 
     * @param evt Event yang dipicu saat pilihan menu akun diubah
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        String memilih = jComboBox1.getSelectedItem().toString();
        
        //Merefresh halaman profil
        if(memilih.equals("Profil")){
            new FrameProfilUser().setVisible(true);
            dispose();
        } else if(memilih.equals("Keluar")){
            //Logout dan kembali ke halaman login
            JOptionPane.showMessageDialog(this, "Selamat tinggal!");
            new FormLogin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * Event handler untuk tombol untuk melihat status pemesanan.
     * Akan menutup form saat ini dan membuka halaman FrameStatusPemesanan.
     * 
     * @param evt Event yang dipicu saat tombol diklik
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new FrameStatusPemesanan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Handler saat comboBox kategori destinasi diklik.
     * Memeriksa kategori yang dipilih dan membuka frame kategori terkait.
     */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String kategoriDipilih = jComboBox2.getSelectedItem().toString();
        if(kategoriDipilih.equals("Destinasi Candi & Pura")){
            new FrameKategoriCandiPura().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Danau & Kepulauan")){
            new FrameKategoriDanauPulau().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Gunung")){
            new FrameKategoriGunung().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Kawah")){
            new FrameKategoriKawah().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Pantai")){
            new FrameKategoriPantai().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Museum")){
            new FrameKategoriMuseum().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Kota & Budaya")){
            new FrameKategoriWisataKotaBudaya().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Alam & Satwa")){
            new FrameKategoriWisataAlamSatwa().setVisible(true);
            dispose();
        }
        if(kategoriDipilih.equals("Destinasi Wisata Buatan (Taman Hiburan)")){
            new FrameKategoriWisataBuatan().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProfilUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameProfilUser().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputKataSandi;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomorPonsel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField konfrKataSandi;
    // End of variables declaration//GEN-END:variables
}
